/** Generate the checked-in Windows icon from the desktop brand mark. */

import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import { DESKTOP_WHALE_PATH } from '../src/startup-page.ts'

const ICON_SIZES = [16, 20, 24, 32, 40, 48, 64, 128, 256] as const
const OUTPUT_DIRECTORY = fileURLToPath(new URL('../build/', import.meta.url))
const SVG_PATH = fileURLToPath(new URL('../build/icon.svg', import.meta.url))
const ICO_PATH = fileURLToPath(new URL('../build/icon.ico', import.meta.url))

function iconSvg(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by apps/desktop/scripts/generate-icon.ts. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <rect x="32" y="32" width="960" height="960" rx="216" fill="#fbfbff" stroke="#dfe0ec" stroke-width="12"/>
  <g transform="translate(146 243) scale(31.6)">
    <path d="${DESKTOP_WHALE_PATH}" fill="#11121a"/>
  </g>
</svg>
`
}

function encodeIco(images: ReadonlyArray<{ size: number; png: Buffer }>): Buffer {
  const directoryLength = 6 + images.length * 16
  const outputLength = directoryLength + images.reduce((total, image) => total + image.png.length, 0)
  const output = Buffer.alloc(outputLength)
  output.writeUInt16LE(0, 0)
  output.writeUInt16LE(1, 2)
  output.writeUInt16LE(images.length, 4)
  let imageOffset = directoryLength
  images.forEach((image, index) => {
    const entryOffset = 6 + index * 16
    output.writeUInt8(image.size === 256 ? 0 : image.size, entryOffset)
    output.writeUInt8(image.size === 256 ? 0 : image.size, entryOffset + 1)
    output.writeUInt8(0, entryOffset + 2)
    output.writeUInt8(0, entryOffset + 3)
    output.writeUInt16LE(1, entryOffset + 4)
    output.writeUInt16LE(32, entryOffset + 6)
    output.writeUInt32LE(image.png.length, entryOffset + 8)
    output.writeUInt32LE(imageOffset, entryOffset + 12)
    image.png.copy(output, imageOffset)
    imageOffset += image.png.length
  })
  return output
}

async function generateIcon(): Promise<void> {
  const svg = iconSvg()
  const source = Buffer.from(svg)
  const images = await Promise.all(ICON_SIZES.map(async size => ({
    size,
    png: await sharp(source).resize(size, size).png({ compressionLevel: 9 }).toBuffer(),
  })))
  await mkdir(OUTPUT_DIRECTORY, { recursive: true })
  await Promise.all([
    writeFile(SVG_PATH, svg),
    writeFile(ICO_PATH, encodeIco(images)),
  ])
}

await generateIcon()
